
import React, { useState } from 'react';
import Layout from '@/components/Layout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Search, BookOpen, MessageCircle, Video, FileText, HelpCircle, ChevronDown, ChevronRight } from 'lucide-react';

const Help = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFAQ, setExpandedFAQ] = useState<number | null>(null);

  const categories = [
    {
      icon: BookOpen,
      title: "Getting Started",
      description: "Learn the basics of FlowForge",
      articles: 12,
      color: "blue"
    },
    {
      icon: FileText,
      title: "Creating SOPs",
      description: "How to generate and customize SOPs",
      articles: 18,
      color: "green"
    },
    {
      icon: Video,
      title: "Visual Workflows",
      description: "Working with flowcharts and diagrams",
      articles: 8,
      color: "purple"
    },
    {
      icon: MessageCircle,
      title: "Collaboration",
      description: "Team features and sharing",
      articles: 10,
      color: "orange"
    }
  ];

  const popularArticles = [
    "How to create your first SOP",
    "Understanding AI-generated content",
    "Exporting SOPs to different formats",
    "Setting up team workspaces",
    "Customizing SOP templates",
    "Using the visual workflow editor"
  ];

  const faqs = [
    {
      question: "How do I create my first SOP?",
      answer: "Creating your first SOP is simple! Click on 'Generate New SOP' in your dashboard, describe your process in plain English, and our AI will create a comprehensive SOP for you. You can then edit, customize, and export it as needed."
    },
    {
      question: "Can I customize the AI-generated SOPs?",
      answer: "Absolutely! Every SOP generated by FlowForge can be fully customized. You can edit steps, add details, modify descriptions, reorder processes, and even add your own branding and formatting."
    },
    {
      question: "What export formats are supported?",
      answer: "FlowForge supports multiple export formats including PDF, Word (DOCX), HTML, and plain text. Pro users also have access to custom templates and branded exports."
    },
    {
      question: "How does team collaboration work?",
      answer: "Team collaboration allows you to share SOPs with colleagues, collect feedback, track changes, and maintain version control. Team members can comment, suggest edits, and work together in real-time."
    },
    {
      question: "Is my data secure?",
      answer: "Yes, we take security seriously. All data is encrypted in transit and at rest, stored in SOC 2 compliant data centers, and we never share your information with third parties. You own your data completely."
    },
    {
      question: "Can I integrate FlowForge with other tools?",
      answer: "Yes! FlowForge offers API integration and works with popular tools like Slack, Microsoft Teams, Google Workspace, and more. Enterprise customers can request custom integrations."
    }
  ];

  const toggleFAQ = (index: number) => {
    setExpandedFAQ(expandedFAQ === index ? null : index);
  };

  return (
    <Layout title="Help Center">
      <div className="space-y-12">
        {/* Search Section */}
        <div className="text-center">
          <p className="text-xl text-[#EEEEEE] font-inter max-w-4xl mx-auto leading-relaxed mb-8">
            Find answers to your questions, learn how to use FlowForge effectively, and get the most out of our platform.
          </p>
          
          <div className="max-w-2xl mx-auto relative">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
            <Input
              type="text"
              placeholder="Search for help articles, guides, or FAQs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-12 pr-4 py-3 text-lg"
            />
            <Button className="absolute right-2 top-1/2 transform -translate-y-1/2">
              Search
            </Button>
          </div>
        </div>

        {/* Help Categories */}
        <div>
          <h2 className="text-3xl font-bold text-white mb-8 text-center font-montserrat">Browse by Category</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {categories.map((category, index) => (
              <Card key={index} className="bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1 cursor-pointer">
                <CardHeader className="text-center">
                  <div className="flex justify-center mb-4">
                    <div className={`p-3 rounded-lg bg-${category.color}-100 dark:bg-${category.color}-900`}>
                      <category.icon className={`h-8 w-8 text-${category.color}-600`} />
                    </div>
                  </div>
                  <CardTitle className="text-white font-montserrat text-xl">{category.title}</CardTitle>
                  <CardDescription className="text-[#EEEEEE] font-inter">{category.description}</CardDescription>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-sm text-[#EEEEEE] font-inter">
                    {category.articles} articles
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Popular Articles */}
        <Card className="bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg">
          <CardHeader>
            <CardTitle className="text-white font-montserrat text-2xl">Popular Articles</CardTitle>
            <CardDescription className="text-[#EEEEEE] font-inter">
              The most helpful articles from our knowledge base
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {popularArticles.map((article, index) => (
                <div 
                  key={index}
                  className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-white/5 transition-colors cursor-pointer"
                >
                  <BookOpen className="h-5 w-5 text-white drop-shadow-lg" />
                  <span className="text-[#EEEEEE] font-inter hover:text-blue-400 transition-colors">
                    {article}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* FAQ Section */}
        <div>
          <h2 className="text-3xl font-bold text-white mb-8 text-center font-montserrat">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <Card key={index} className="overflow-hidden bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg">
                <CardContent className="p-0">
                  <button
                    onClick={() => toggleFAQ(index)}
                    className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-white/5 transition-colors"
                  >
                    <span className="font-medium text-white pr-4">
                      {faq.question}
                    </span>
                    {expandedFAQ === index ? (
                      <ChevronDown className="h-5 w-5 text-gray-500 flex-shrink-0" />
                    ) : (
                      <ChevronRight className="h-5 w-5 text-gray-500 flex-shrink-0" />
                    )}
                  </button>
                  {expandedFAQ === index && (
                    <div className="px-6 pb-4 pt-0">
                      <p className="text-[#EEEEEE] font-inter leading-relaxed">
                        {faq.answer}
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Contact Support */}
        <Card className="bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg">
          <CardContent className="pt-6 text-center">
            <HelpCircle className="h-12 w-12 text-brand-blue mx-auto mb-4 drop-shadow-lg" />
            <h3 className="text-2xl font-bold text-white mb-4 font-montserrat">
              Still Need Help?
            </h3>
            <p className="text-[#EEEEEE] font-inter mb-6 max-w-2xl mx-auto">
              Can't find what you're looking for? Our support team is here to help you get the most out of FlowForge.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Button className="btn-premium font-montserrat text-white text-lg shadow-xl px-8 py-3 rounded-xl">Contact Support</Button>
              <Button variant="outline" className="border border-brand-blue/70 bg-white/10 text-white font-montserrat hover:bg-brand-blue hover:text-white transition px-8 py-3 rounded-xl">Schedule a Demo</Button>
            </div>
          </CardContent>
        </Card>

        {/* Quick Links */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="text-center hover:shadow-2xl transition-shadow bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg group">
            <CardContent className="pt-8 pb-6 flex flex-col items-center">
              <Video className="h-10 w-10 text-white drop-shadow-lg mb-3 group-hover:scale-110 transition-transform" />
              <h4 className="font-semibold text-white mb-2 font-montserrat text-lg">Video Tutorials</h4>
              <p className="text-sm text-[#EEEEEE] font-inter mb-6">Watch step-by-step video guides</p>
              <a href="#" target="_blank" rel="noopener noreferrer" className="w-full">
                <Button className="w-full btn-premium font-montserrat text-white text-base shadow-xl px-6 py-3 rounded-xl hover:scale-[1.03] transition-transform">View Videos</Button>
              </a>
            </CardContent>
          </Card>

          <Card className="text-center hover:shadow-2xl transition-shadow bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg group">
            <CardContent className="pt-8 pb-6 flex flex-col items-center">
              <MessageCircle className="h-10 w-10 text-white drop-shadow-lg mb-3 group-hover:scale-110 transition-transform" />
              <h4 className="font-semibold text-white mb-2 font-montserrat text-lg">Community Forum</h4>
              <p className="text-sm text-[#EEEEEE] font-inter mb-6">Connect with other FlowForge users</p>
              <a href="#" target="_blank" rel="noopener noreferrer" className="w-full">
                <Button className="w-full btn-premium font-montserrat text-white text-base shadow-xl px-6 py-3 rounded-xl hover:scale-[1.03] transition-transform">Join Community</Button>
              </a>
            </CardContent>
          </Card>

          <Card className="text-center hover:shadow-2xl transition-shadow bg-white/10 backdrop-blur-md border border-flowforge-gray text-white shadow-lg group">
            <CardContent className="pt-8 pb-6 flex flex-col items-center">
              <FileText className="h-10 w-10 text-white drop-shadow-lg mb-3 group-hover:scale-110 transition-transform" />
              <h4 className="font-semibold text-white mb-2 font-montserrat text-lg">API Documentation</h4>
              <p className="text-sm text-[#EEEEEE] font-inter mb-6">Technical documentation for developers</p>
              <a href="#" target="_blank" rel="noopener noreferrer" className="w-full">
                <Button className="w-full btn-premium font-montserrat text-white text-base shadow-xl px-6 py-3 rounded-xl hover:scale-[1.03] transition-transform">View Docs</Button>
              </a>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  );
};

export default Help;
